// GENERATED by scripts/sync_examples.py -- do not edit by hand.
// Documents are embedded so the demo needs no second network call.

export type Example = {
  id: string;
  label: string;
  caption: string;
  domain: string;
  text: string;
  gold: Record<string, unknown> | null;
};

export const EXAMPLES: Example[] = [
  {
    "id": "invoice_currency_symbols",
    "label": "currency symbols",
    "caption": "invented vendor id, plus codes that don't match the code format",
    "domain": "invoice",
    "text": "INVOICE\n\nInvoice #: JAP-94121346\nDate Issued: 2026-04-08\nDue Date: 2026-05-08\n\nFrom:\nDunmore Electrical Co\n200 Bay Street, Toronto, ON M5J 2J1, Canada\nTax ID: TX168683\n\nBill To:\nHalcyon Studios LLC\n1200 Congress Ave, Austin, TX 78701, USA\nTax ID: —\n\n-----------------------------------------------------------------\n\n| Description | Qty | Unit Price | Amount |\n|-------------|-----|------------|--------|\n| Crane hire, half day | 12.00 | $35.10 | 421.20 dollars |\n| Courier service, zone 3 | 5.00 | 220.74 USD | 1,103.70 USD |\n| Hex bolt M10x60 (box of 50) | 2.00 | USD 53.61 | $107.22 |\n\n-----------------------------------------------------------------\n\nSubtotal: $1,632.12 USD\nTax: 0.00\nDiscount: 0.00 dollars\n\nTOTAL DUE: 1,632.12 $",
    "gold": {
      "invoice_number": "JAP-94121346",
      "issue_date": "2026-04-08",
      "due_date": "2026-05-08",
      "currency": "USD",
      "payment_terms": "NET_30",
      "vendor_id": "VND-00921",
      "vendor": {
        "name": "Dunmore Electrical Co",
        "address": "200 Bay Street, Toronto, ON M5J 2J1, Canada",
        "tax_id": "TX168683"
      },
      "bill_to": {
        "name": "Halcyon Studios LLC",
        "address": "1200 Congress Ave, Austin, TX 78701, USA",
        "tax_id": null
      },
      "line_items": [
        {
          "description": "Crane hire, half day",
          "category": "SV-RENT-15",
          "quantity": "12.00",
          "unit_price": "35.10",
          "line_total": "421.20"
        },
        {
          "description": "Courier service, zone 3",
          "category": "SV-COUR-08",
          "quantity": "5.00",
          "unit_price": "220.74",
          "line_total": "1103.70"
        },
        {
          "description": "Hex bolt M10x60 (box of 50)",
          "category": "HW-FAST-05",
          "quantity": "2.00",
          "unit_price": "53.61",
          "line_total": "107.22"
        }
      ],
      "subtotal": "1632.12",
      "tax": "0.00",
      "discount": "0.00",
      "total": "1632.12"
    }
  },
  {
    "id": "invoice_missing_totals",
    "label": "missing totals",
    "caption": "invents a vendor id and all 5 category codes; totals aren't printed",
    "domain": "invoice",
    "text": "Solvent Chemical Co\n3 Dock Lane, Hull HU1 2AB, UK\n\nINVOICE #: SGC-53476538\nDate: 2026-05-01\nDue: 2026-05-01\nCurrency: EUR\n\nBill To:\nRiverbend Outfitters\n77 Queen St E, Ottawa, ON K1P 5C8, Canada\n\n---------------------------------------------------------\n\nItem                           Qty      Unit Price     Amount\nSafety boots, size 10          12.00    61.73          740.76\nSteel shelf bracket, heavy     5.00     305.39         1526.95\nInkjet cartridge, black        3.00     335.54         1006.62\nThermal receipt roll 80mm      100.00   179.06         17906.00\nArgon cylinder, 50L            10.00    325.47         3254.70\n\n---------------------------------------------------------\n\nTax rate applied as per local regulations.\nDiscount applied: 0.00\n\nPayment terms: Due on receipt.\n\nThank you for your business.",
    "gold": {
      "invoice_number": "SGC-53476538",
      "issue_date": "2026-05-01",
      "due_date": "2026-05-01",
      "currency": "EUR",
      "payment_terms": "DUE_ON_RECEIPT",
      "vendor_id": "VND-01530",
      "vendor": {
        "name": "Solvent Chemical Co",
        "address": "3 Dock Lane, Hull HU1 2AB, UK",
        "tax_id": null
      },
      "bill_to": {
        "name": "Riverbend Outfitters",
        "address": "77 Queen St E, Ottawa, ON K1P 5C8, Canada",
        "tax_id": null
      },
      "line_items": [
        {
          "description": "Safety boots, size 10",
          "category": "PE-BOOT-07",
          "quantity": "12.00",
          "unit_price": "61.73",
          "line_total": "740.76"
        },
        {
          "description": "Steel shelf bracket, heavy",
          "category": "HW-MOUN-14",
          "quantity": "5.00",
          "unit_price": "305.39",
          "line_total": "1526.95"
        },
        {
          "description": "Inkjet cartridge, black",
          "category": "PP-INKJ-02",
          "quantity": "3.00",
          "unit_price": "335.54",
          "line_total": "1006.62"
        },
        {
          "description": "Thermal receipt roll 80mm",
          "category": "PP-ROLL-01",
          "quantity": "100.00",
          "unit_price": "179.06",
          "line_total": "17906.00"
        },
        {
          "description": "Argon cylinder, 50L",
          "category": "CH-GASS-04",
          "quantity": "10.00",
          "unit_price": "325.47",
          "line_total": "3254.70"
        }
      ],
      "subtotal": "24435.03",
      "tax": "1221.75",
      "discount": "0.00",
      "total": "25656.78"
    }
  },
  {
    "id": "invoice_scanned_fax",
    "label": "scanned fax",
    "caption": "OCR artefacts across 5 line items",
    "domain": "invoice",
    "text": "---\n\n**FAX TRANSMISSION REPORT**\n==================================================\nFROM: -------------- TO: --------------------\nDATE: 2026-04-26 TIME: 14:32:07\nPAGES: 01/01 STATUS: OK [##########]\n==================================================\n--- CONFIDENTIAL ---\nPAGE 1 OF 1\nREF: BJD-81347720\n==================================================\n\n---\n\nINVOICE\n\nNo. BJD-81347720\n\nDate: 2026-04-26\n\n---\n\nVENDOR:\n\nKestrel Fasteners plc\n58 Attercliffe Road, Sheffield S4 7WL, UK\n\n---\n\nBILL TO:\n\nAubergine Foods SARL\n22 Rue Saint-Denis, 75001 Paris, France\n\n---\n\nDUE DATE: 2026-04-26\n\nCURRENCY: EUR\n\n---\n\n| Description | Qty | Unit Price | Amount |\n|-------------|-----|------------|--------|\n| Hi-vis vest, XL | 5.00 | 285.47 | 1427.35 |\n| Warehouse handling fee | 5.00 | 455.19 | 2275.95 |\n| Corrugated box 400x300x200 | 3.00 | 151.19 | 453.57 |\n| Industrial adhesive 5L | 2.00 | 230.17 | 460.34 |\n| Ear defenders, class 4 | 100.00 | 250.61 | 25061.00 |\n\n---\n\nSUBTOTAL: 29678.21\n\nTAX: 0.00\n\nDISCOUNT: 0.00\n\n---\n\n**TOTAL: 29678.21**\n\n---\n\n==================================================\n--- END TRANSMISSION ---\nFAX ID: BJD-81347720-P1\n==================================================\n--- PLEASE RECYCLE ---\nPAGE 1 OF 1",
    "gold": {
      "invoice_number": "BJD-81347720",
      "issue_date": "2026-04-26",
      "due_date": "2026-04-26",
      "currency": "EUR",
      "payment_terms": "DUE_ON_RECEIPT",
      "vendor_id": "VND-01443",
      "vendor": {
        "name": "Kestrel Fasteners plc",
        "address": "58 Attercliffe Road, Sheffield S4 7WL, UK",
        "tax_id": null
      },
      "bill_to": {
        "name": "Aubergine Foods SARL",
        "address": "22 Rue Saint-Denis, 75001 Paris, France",
        "tax_id": null
      },
      "line_items": [
        {
          "description": "Hi-vis vest, XL",
          "category": "PE-VEST-01",
          "quantity": "5.00",
          "unit_price": "285.47",
          "line_total": "1427.35"
        },
        {
          "description": "Warehouse handling fee",
          "category": "SV-HAND-01",
          "quantity": "5.00",
          "unit_price": "455.19",
          "line_total": "2275.95"
        },
        {
          "description": "Corrugated box 400x300x200",
          "category": "PK-BOXX-03",
          "quantity": "3.00",
          "unit_price": "151.19",
          "line_total": "453.57"
        },
        {
          "description": "Industrial adhesive 5L",
          "category": "CH-ADHE-03",
          "quantity": "2.00",
          "unit_price": "230.17",
          "line_total": "460.34"
        },
        {
          "description": "Ear defenders, class 4",
          "category": "PE-EARS-05",
          "quantity": "100.00",
          "unit_price": "250.61",
          "line_total": "25061.00"
        }
      ],
      "subtotal": "29678.21",
      "tax": "0.00",
      "discount": "0.00",
      "total": "29678.21"
    }
  }
];
