"""Baseten Training Jobs backend.

A Baseten training job is a DIRECTORY, not a config file: `config.py` declares
the image and compute, `run.sh` installs deps and starts training, `train.py`
does the work, and anything else in the directory is uploaded with it. We
generate all four per run and drop the dataset in alongside.

    truss train push <jobdir>/config.py
    truss train deploy_checkpoints --config <deploydir>/deploy.py

`deploy_checkpoints` is INTERACTIVE by default -- it prompts for checkpoint,
model name and GPU. That is fine by hand and useless unattended, so we always
generate a DeployCheckpointsConfig and pass `--config`.

Reference timing from Baseten's own qwen3-4b LoRA SFT example: ~2 minutes on
1x H100 for 50 steps. Training is not the demo bottleneck; queueing and
deployment are.

`DRY_RUN=1` skips the real job and returns a synthetic id, so the whole loop
stays exercisable offline.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import uuid
from datetime import datetime
from pathlib import Path

from core.config import ROOT, settings

JOBS_DIR = ROOT / "train" / "jobs"

CONFIG_PY = '''"""Generated by train/backend.py -- do not hand-edit."""
from truss_train import (
    TrainingProject, TrainingJob, Image, Compute, Runtime,
    CacheConfig, CheckpointingConfig,
)
from truss.base.truss_config import AcceleratorSpec

BASE_IMAGE = "pytorch/pytorch:2.7.0-cuda12.8-cudnn9-runtime"

training_runtime = Runtime(
    start_commands=["chmod +x ./run.sh && ./run.sh"],
    cache_config=CacheConfig(enabled=True),
    checkpointing_config=CheckpointingConfig(enabled=True),
)

training_compute = Compute(
    accelerator=AcceleratorSpec(accelerator="{accelerator}", count={gpu_count}),
)

training_job = TrainingJob(
    image=Image(base_image=BASE_IMAGE),
    compute=training_compute,
    runtime=training_runtime,
)

training_project = TrainingProject(name="{run_name}", job=training_job)
'''

RUN_SH = """#!/bin/bash
set -eux
pip install "trl>=0.20.0" "peft>=0.17.0" "transformers>=4.55.0" "datasets"
python train.py
"""

TRAIN_PY = '''"""Generated by train/backend.py -- do not hand-edit."""
import os
import torch
from datasets import load_dataset
from peft import LoraConfig
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import SFTConfig, SFTTrainer

MODEL_ID = "{base_model}"

# The dataset ships inside the job directory, so no hub download and no
# chance of training on something other than what we built.
dataset = load_dataset("json", data_files="dataset.jsonl", split="train")
print(f"loaded {{len(dataset)}} examples")

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID, torch_dtype=torch.bfloat16, device_map="auto", use_cache=False,
)

peft_config = LoraConfig(
    r={lora_r},
    lora_alpha={lora_alpha},
    target_modules="all-linear",
    lora_dropout=0.05,
    task_type="CAUSAL_LM",
)

training_args = SFTConfig(
    learning_rate={lr},
    num_train_epochs={epochs},
    logging_steps=5,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=8,
    gradient_checkpointing=True,
    max_length={max_length},
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    save_strategy="epoch",
    bf16=True,
    output_dir=os.getenv("BT_CHECKPOINT_DIR", "./checkpoints"),
)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    processing_class=tokenizer,
    peft_config=peft_config,
)
trainer.train()
trainer.save_model(training_args.output_dir)
print("training complete ->", training_args.output_dir)
'''

DEPLOY_PY = '''"""Generated by train/backend.py -- do not hand-edit."""
from truss_train import (
    DeployCheckpointsConfig, CheckpointList, Checkpoint,
    DeployCheckpointsRuntime, SecretReference, Compute,
)
from truss.base.truss_config import AcceleratorSpec

deploy_checkpoints_config = DeployCheckpointsConfig(
    checkpoint_details=CheckpointList(
        download_folder="/tmp/checkpoints",
        base_model_id="{base_model}",
        checkpoints=[
            Checkpoint(
                training_job_id="{job_id}",
                checkpoint_name="{checkpoint_name}",
                model_weight_format="lora",
            )
        ],
    ),
    model_name="{model_name}",
    runtime=DeployCheckpointsRuntime(
        environment_variables={{"HF_TOKEN": SecretReference(name="hf_access_token")}}
    ),
    compute=Compute(accelerator=AcceleratorSpec(accelerator="{accelerator}", count=1)),
)
'''


def detect_cli() -> str | None:
    """Find the Baseten CLI, preferring the official `baseten` binary.

    `truss train push` hits /v1/teams/<team>/training_projects and returned
    403 "not authorized for Baseten training" on this account, while the
    official `baseten` CLI reads the same resources fine -- so truss appears
    to use a legacy endpoint. Prefer `baseten`; keep `truss` as a fallback.

    Search order matters on Windows: a venv's Scripts/ is not on PATH unless
    activated, and we vendor the official binary into .tools/.
    """
    bindir = Path(sys.executable).parent
    for candidate in ("baseten", "truss"):
        for directory in (ROOT / ".tools", bindir):
            for suffix in (".exe", ""):
                local = directory / f"{candidate}{suffix}"
                if local.exists():
                    return str(local)
        found = shutil.which(candidate)
        if found:
            return found
    return None


def is_official_cli(cli: str) -> bool:
    """The two CLIs disagree on flags: `baseten` takes --config, truss positional."""
    return Path(cli).stem.lower() == "baseten"


class TruncationError(RuntimeError):
    """Raised when examples would be silently cut off during training."""


def assert_fits(dataset_path: str | Path, max_length: int, chars_per_token: float = 3.0) -> dict:
    """Refuse to launch a run whose examples would be truncated.

    Our system prompt embeds the full JSON Schema (~5.9k chars), so a single
    example runs well past the 2048 default that Baseten's sample configs use.
    SFTTrainer truncates from the RIGHT, which removes the assistant's answer
    -- the model would train on prompts with no target and produce garbage,
    with nothing in the logs to say so.

    chars_per_token is deliberately conservative (3.0, vs ~3.5-4 typical for
    English JSON) so the estimate errs toward over-counting.
    """
    path = Path(dataset_path)
    longest = 0
    count = 0
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        count += 1
        longest = max(
            longest,
            sum(len(m["content"]) for m in json.loads(line)["messages"]),
        )

    est_tokens = int(longest / chars_per_token)
    if est_tokens > max_length:
        raise TruncationError(
            f"longest example is ~{est_tokens} tokens ({longest} chars) but "
            f"max_length={max_length}. The assistant's answer would be cut "
            f"off and the run would train on targetless prompts.\n"
            f"Raise max_length to >= {((est_tokens // 512) + 1) * 512}, or "
            f"shorten the system prompt in serve/extract.py (note: it must "
            f"stay identical between training and serving)."
        )
    return {"examples": count, "longest_chars": longest,
            "est_tokens": est_tokens, "max_length": max_length}


def cli_env() -> dict:
    """Environment for the truss subprocess.

    truss authenticates from ~/.trussrc, which our .env does not populate.
    Rather than writing the API key to a new file on disk, pass it through the
    subprocess environment. Also disables interactive prompts -- a CLI that
    stops to ask a question in a background subprocess just hangs forever.
    """
    env = dict(os.environ)
    env["BASETEN_API_KEY"] = settings.require_key()
    env["NO_COLOR"] = "1"
    env["TERM"] = "dumb"
    return env


def dry_run_enabled() -> bool:
    if os.getenv("DRY_RUN") is not None:
        return os.getenv("DRY_RUN") == "1"
    return not settings.baseten_api_key


def build_job(
    dataset_path: str,
    run_name: str,
    *,
    lora_r: int = 16,
    lora_alpha: int | None = None,
    epochs: int = 3,
    lr: float = 2e-4,
    max_length: int = 4096,
    accelerator: str = "H100",
    gpu_count: int = 1,
) -> Path:
    """Materialise a complete training job directory. Returns its path."""
    if lora_r not in {8, 16, 32, 64, 128, 256, 320, 512}:
        raise ValueError(f"lora_r={lora_r} is not a rank Baseten accepts")

    assert_fits(dataset_path, max_length)

    job_dir = JOBS_DIR / run_name
    job_dir.mkdir(parents=True, exist_ok=True)

    (job_dir / "config.py").write_text(
        CONFIG_PY.format(run_name=run_name, accelerator=accelerator,
                         gpu_count=gpu_count),
        encoding="utf-8",
    )
    (job_dir / "run.sh").write_text(RUN_SH, encoding="utf-8", newline="\n")
    (job_dir / "train.py").write_text(
        TRAIN_PY.format(
            base_model=settings.train_base_model,
            lora_r=lora_r,
            lora_alpha=lora_alpha or lora_r * 2,
            epochs=epochs,
            lr=lr,
            max_length=max_length,
        ),
        encoding="utf-8",
    )
    shutil.copyfile(dataset_path, job_dir / "dataset.jsonl")
    return job_dir


def launch(dataset_path: str, run_name: str | None = None, **kwargs) -> dict:
    """Push a training job. Returns {job_id, job_dir, dry_run, run_name}."""
    run_name = run_name or f"autoextract-{datetime.now():%Y%m%d-%H%M%S}"
    job_dir = build_job(dataset_path, run_name, **kwargs)

    if dry_run_enabled():
        return {"job_id": f"dry-{uuid.uuid4().hex[:12]}", "job_dir": str(job_dir),
                "dry_run": True, "run_name": run_name}

    cli = detect_cli()
    if cli is None:
        raise RuntimeError(
            "Neither `baseten` nor `truss` found. `pip install truss`, or set "
            "DRY_RUN=1 to exercise the loop without training."
        )

    config = str(job_dir / "config.py")
    argv = (
        [cli, "train", "push", "--config", config, "--job-name", run_name]
        if is_official_cli(cli)
        else [cli, "train", "push", config, "--job-name", run_name]
    )
    result = subprocess.run(
        argv,
        capture_output=True, text=True, cwd=job_dir, env=cli_env(),
        stdin=subprocess.DEVNULL, timeout=900,
        # truss prints box-drawing characters; the Windows default cp1252
        # decode raises UnicodeDecodeError and loses the whole output.
        encoding="utf-8", errors="replace",
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"train push failed (exit {result.returncode}):\n"
            f"{result.stdout[-2000:]}\n{result.stderr[-2000:]}"
        )

    return {"job_id": _parse_job_id(result.stdout), "job_dir": str(job_dir),
            "dry_run": False, "run_name": run_name, "stdout": result.stdout}


def deploy_checkpoint(
    job_id: str,
    *,
    checkpoint_name: str = "latest",
    model_name: str | None = None,
    accelerator: str = "H100",
) -> dict:
    """Deploy a finished job's LoRA checkpoint as a served endpoint."""
    if job_id.startswith("dry-"):
        return {"adapter_ref": f"{settings.train_base_model}:{job_id}", "dry_run": True}

    cli = detect_cli()
    if cli is None:
        raise RuntimeError("Baseten CLI not found.")

    model_name = model_name or f"autoextract-{job_id[:8]}"
    deploy_dir = JOBS_DIR / "_deploy"
    deploy_dir.mkdir(parents=True, exist_ok=True)
    deploy_path = deploy_dir / f"deploy-{job_id[:12]}.py"
    deploy_path.write_text(
        DEPLOY_PY.format(
            base_model=settings.train_base_model,
            job_id=job_id,
            checkpoint_name=checkpoint_name,
            model_name=model_name,
            accelerator=accelerator,
        ),
        encoding="utf-8",
    )

    result = subprocess.run(
        [cli, "train", "deploy_checkpoints", "--config", str(deploy_path)],
        capture_output=True, text=True, cwd=ROOT, env=cli_env(),
        stdin=subprocess.DEVNULL, timeout=1800,
        encoding="utf-8", errors="replace",
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"deploy_checkpoints failed (exit {result.returncode}):\n"
            f"{result.stdout[-2000:]}\n{result.stderr[-2000:]}\n"
            "If this mentions a missing token, add `hf_access_token` at "
            "https://app.baseten.co/settings/secrets"
        )
    return {"adapter_ref": _parse_model_id(result.stdout) or model_name,
            "dry_run": False, "deploy_config": str(deploy_path),
            "stdout": result.stdout}


def job_status(job_id: str) -> str:
    """Best-effort status poll. Returns raw CLI text."""
    cli = detect_cli()
    if cli is None or job_id.startswith("dry-"):
        return "unknown"
    result = subprocess.run(
        [cli, "train", "logs", "--job-id", job_id],
        capture_output=True, text=True, cwd=ROOT, env=cli_env(),
        stdin=subprocess.DEVNULL, timeout=120,
        encoding="utf-8", errors="replace",
    )
    return result.stdout[-4000:] or result.stderr[-2000:]


def _parse_job_id(stdout: str) -> str:
    import re
    m = re.search(r"\b([a-z0-9]{6,}-[a-z0-9-]{6,})\b", stdout)
    if m:
        return m.group(1)
    for line in stdout.splitlines():
        low = line.lower()
        if "job" in low and "id" in low:
            parts = line.replace(":", " ").split()
            if parts:
                return parts[-1].strip()
    return stdout.strip().splitlines()[-1].strip() if stdout.strip() else "unknown"


def _parse_model_id(stdout: str) -> str | None:
    for line in stdout.splitlines():
        low = line.lower()
        if "model" in low and ("id" in low or "deploy" in low):
            parts = line.replace(":", " ").split()
            if parts:
                return parts[-1].strip()
    return None
