"""Generate dashboard/app/examples.ts from the examples/ directory.

The documents are EMBEDDED in the bundle rather than fetched. A demo should
not depend on a second network call working, and these files change about
once a week -- regenerating on demand is cheaper than a live endpoint.

    python scripts/sync_examples.py
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"
OUT = ROOT / "dashboard" / "app" / "examples.ts"

#: Display order and the one-line "what this shows" caption, keyed by stem.
#: Anything in examples/ without an entry here still ships, captionless.
CAPTIONS: dict[str, tuple[str, str]] = {
    "invoice_missing_totals": (
        "missing totals",
        "invents a vendor id and all 5 category codes; totals aren't printed",
    ),
    "invoice_currency_symbols": (
        "currency symbols",
        "invented vendor id, plus codes that don't match the code format",
    ),
    "invoice_scanned_fax": (
        "scanned fax",
        "OCR artefacts across 5 line items",
    ),
    "email_billing": (
        "billing email",
        "customer id, category and priority are nowhere in the text",
    ),
    "email_technical": (
        "technical email",
        "gold-tier customer, so a technical ticket escalates to P1",
    ),
}


def main() -> None:
    docs = sorted(EXAMPLES.glob("*.txt"))
    if not docs:
        sys.exit("no examples/*.txt found")

    entries = []
    for path in docs:
        stem = path.stem
        label, caption = CAPTIONS.get(stem, (stem.replace("_", " "), ""))
        text = path.read_text(encoding="utf-8").strip()
        gold_path = path.with_suffix(".gold.json")
        gold = None
        if gold_path.exists():
            gold = json.loads(gold_path.read_text(encoding="utf-8"))
        entries.append({
            "id": stem,
            "label": label,
            "caption": caption,
            "domain": "support_email" if stem.startswith("email") else "invoice",
            "text": text,
            # The FULL gold, so the playground can say "valid but still wrong"
            # rather than only "valid". That distinction is the demo's most
            # important beat and it needs ground truth to make it.
            "gold": gold,
        })

    body = json.dumps(entries, indent=2, ensure_ascii=False)
    OUT.write_text(
        "// GENERATED by scripts/sync_examples.py -- do not edit by hand.\n"
        "// Documents are embedded so the demo needs no second network call.\n\n"
        "export type Example = {\n"
        "  id: string;\n"
        "  label: string;\n"
        "  caption: string;\n"
        "  domain: string;\n"
        "  text: string;\n"
        "  gold: Record<string, unknown> | null;\n"
        "};\n\n"
        f"export const EXAMPLES: Example[] = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(entries)} examples)")
    for e in entries:
        print(f"  {e['id']:<28} {len(e['text']):>5} chars  {e['label']}")


if __name__ == "__main__":
    main()
